### ISSUE TITLE
index.js:9 Uncaught TypeError: request.get(...).buffer is not a function

### ISSUE THREAD

**Issue by armenzg** [mozilla/telemetry-next-node#2]
CC @chutten 

I'm trying to vendor telemetry-wrapper.js.
I make reference to it:
> import '../vendor/telemetry-wrapper';
then I call it:
> TelemetryWrapper.go(plot, node);

Inside of telemetry-wrapper.js I add the following line:
> import Telemetry from 'telemetry-next-node';

Unfortunately this approach throws the following:
```
index.js:9 Uncaught TypeError: request.get(...).buffer is not a function
    at Object.exports.init (index.js:9)
    at Object.window.TelemetryWrapper.go (telemetry-wrapper.js:28)
```

Line 9 is the following:
https://github.com/mozilla/telemetry-next-node/blob/master/index.js#L9
```
exports.init = function(cb) {
  request
    .get('https://telemetry.mozilla.org/v2/telemetry.js')
    .buffer()
.end(function(err, res) {
```

**Comment by chutten** [comment]
Maybe you have a different version of "superagent" which has a different API for request?

**Comment by armenzg** [comment]
Maybe.
Perhaps its a good time to add yarn and lock the dependencies.

**Comment by armenzg** [comment]
This is what I currently have:
```
platform-health-dashboard@0.0.1 /Users/armenzg/repos/platform-health
├─┬ supertest@3.0.0
│ └── superagent@3.5.2
└─┬ telemetry-next-node@1.2.0
  └── superagent@0.17.0
```

**Comment by armenzg** [comment]
Removing buffer() shows another issue:
> Failed to load https://telemetry.mozilla.org/v2/telemetry.js: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Would you be able to help me find someone that could help bring the package to our present? Or guide me on how to do so?

I believe the right long term solution is keep supporting this package rather than needing to fork.

**Comment by armenzg** [comment]
CC @jonasfj 

We can ignore that localhost issue on the previous comment.

What is the way forward for React project to use Telemetry.js?

As you can see @digitarald had to fork the file and place it in here:
https://github.com/mozilla/platform-health/blob/master/src/perf/telemetry-node.js

In my case, I have the need to use from static/ as well because I have to convert an array of evolutions into Evolution objects (e.g. having dates() and other methods):
https://github.com/mozilla/platform-health/pull/18/commits/803df215f1b08cedda49e4c309ac0bad09672153#diff-6971ba22a431a2291ae4e2dc946edb82R30

I've tried to bump the version of superagent, however, I don't know how to properly test this locally:
https://github.com/mozilla/telemetry-next-node/compare/master...armenzg:new_superagent
I use npm link but I was getting complains that the dependency has to be in packages.json, which gets me version 1.2.0 (the published one).
